# Default configurations

# Data directories (can be customized if needed)
price_data_dir: '<USER_DIRECTORY_TOKEN>/retail_pricing/competitor_recognition_data'
store_file_path: '%price_data_dir%/Store_data_git.csv'
subchain_file_path: '%price_data_dir%/SubChainNameEnglish.xlsx'

# NaN threshold for data preprocessing (default to 25%)
nan_threshold: 0.25

# Default methods for dimensionality reduction and clustering
dimensionality_reduction_method: 'pca'
dimensionality_reduction_method_params:
  n_oversamples: 10


clustering_method: 'birch'
clustering_method_params:
  threshold: 9
  n_clusters: null

# Top N competitors to display
top_n_competitors: 5