apiVersion: v1
kind: Service
metadata:
  name: competitive-intelligence-app
spec:
  selector:
    app: competitive-intelligence-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort