# Default configuration for price imputation and forecasting

# Data directories
price_data_dir: "<USER_DIRECTORY_TOKEN>/retail_pricing/competitor_recognition_data"
store_file_path: "%price_data_dir%/Store_data_git.csv"
subchain_file_path: "%price_data_dir%/SubChainNameEnglish.xlsx"

# Preprocessing values
nan_threshold_ratio: 0.75      # Keep observations with at least 75% non-NaN values
fill_nan_value: 0        # Value used for replacing NaNs during masking

# Simulation settings (for artificial missing gaps during training)
gap_prob: 0.3            # Probability of simulating a missing gap
max_gap: 30              # Maximum length of missing gap (in days)

# Train/val/test split
test_size: 0.2
val_size: 0.2
random_state: 42

# Default imputation model
imputation_model: "bi_rnn"
imputation_model_params:
  seq_units: 64
  dense_units: 64
  dropout_rate: 0.3
  epochs: 1
  batch_size: 32
  callbacks: null

# Save settings
model_save_dir_imputation: "./saved_models/imputation/"