# Default configuration for price imputation and forecasting

# Data directories
price_data_dir: "<USER_DIRECTORY_TOKEN>/retail_pricing/competitor_recognition_data"
store_file_path: "%price_data_dir%/Store_data_git.csv"
subchain_file_path: "%price_data_dir%/SubChainNameEnglish.xlsx"

# Preprocessing values
nan_threshold_ratio: 0.75      # Keep observations with at least 75% non-NaN values
fill_nan_value: 0        # Value used for replacing NaNs during masking

# Simulation settings (for artificial missing gaps during training)
gap_prob: 0.3            # Probability of simulating a missing gap
max_gap: 30              # Maximum length of missing gap (in days)

# Sliding window parameters (for forecasting model training)
lookback: 84  # Number of past days to use as input (historical window length)
horizon: 28  # Number of future days to forecast (prediction horizon)
min_stride: 28  # Minimum gap (stride) between starting points of sliding windows
max_stride: 84  # Maximum gap (stride) between sliding windows

# Train/val/test split
test_size: 0.2
val_size: 0.2
random_state: 42

# Default imputation model
imputation_model: "bi_rnn"
imputation_model_params:
  seq_units: 128
  dense_units: 128
  dropout_rate: 0.2
  recurrent_dropout: 0.1
  epochs: 30
  batch_size: 64
  learning_rate: 0.001
  callbacks: null

# Default forecasting model
forecasting_model: "gru"
forecasting_model_params:
  gru_units: 256
  dense_units: 128
  dropout_rate: 0.15
  epochs: 30
  batch_size: 64
  learning_rate: 0.001

# Save settings
model_save_dir_imputation: "./saved_models/imputation/"
model_save_dir_forecasting: "./saved_models/forecasting/"